Traceback (most recent call last):
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 527, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = arange(6) # 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-20-1c7d783cbb6d>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mx[0m [0;34m=[0m [0marange[0m[0;34m([0m[0;36m6[0m[0;34m)[0m [0;31m#[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'arange' is not defined
NameError: name 'arange' is not defined

